# action.yml
name: 'Git Meta'
description: 'A simple Docker action to build the lambdas using SAM and copy the results into S3.'
inputs:
  version:
    description: 'The version of the service'
    required: true
  name:
    description: 'The name of the service'
    required: true
  bucket:
    description: 'The name of the bucket to put the files into'
    required: true
    default: mavrck-build-artifacts
  use-container:
    description: 'Whether to run sam build with --use-container option'
    required: false
    deprecationMessage: 'Deprecated in favor of more generic sam-build-options input'
  sam-build-options:
    description: 'Extra options for sam build command'
    required: false
  sam-package-options:
    description: 'Extra options for sam package command'
    required: false

outputs:
  templateOutput:
    description: 'File path to the generated template file'
runs:
  using: 'node16'
  main: 'dist/index.js'
