# action.yml
name: 'Git Meta'
description: 'A simple Docker action to build the lambdas using SAM and copy the results into S3.'
inputs:
  version:
    description: 'The version of the service'
    required: true
  name:
    description: 'The name of the service'
    required: true
  bucket:
    description: 'The name of the bucket to put the files into'
    required: true
    default: mavrck-builds
  templateOutput:
    description: 'Template output'
    required: true
    default: cf.yml

runs:
  using: 'node12'
  main: 'dist/index.js'
