name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'deploy/**'
      - '.gitignore'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test and prepare distribution
        run: npm install && npm run all

      - run: git status